FROM node:14-alpine As development

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build:production

FROM node:14-alpine as production

WORKDIR /usr/src/app

COPY package*.json ./


RUN npm install --omit=dev

COPY . .

COPY --from=development /usr/src/app/build ./build

RUN npm install -g serve

EXPOSE 3000

CMD ["serve", "-s", "build", "-p", "3000"]